'use strict';
// "nodes":[{"name":"xyz","x":1.2,"y":3.4}]
// "links":[{"name":"abc","nodeIDs":["n1":"n2"]}]
//              or
// "nodes":new Array(nnodes)
// "links":[[3,6],[1,4]]
const configurations = {
    "grid" : {
        "name":"Grid",
        "nports":5,
        "xscale":0.7,"yscale":0.7},
    "baranDistributedGrid": {
        "name":"Baran Distributed Grid",
        "nports":6,
        "xscale":6,"yscale":6,
        "nodes": baranGridNodes(),
        "links": baranDistributedLinks()},
    "baranKleinbergGrid": {
        "name":"Baran + Kleinberg Links",
        "nports":6,
        "xscale":6, "yscale":6, 
        "nodes": baranGridNodes(),
        "links": baranDistributedLinks().concat(baranKleinberg())},
    "baranDistributed": {
        "name":"Baran Distributed",
        "nports":6,
        "xscale":3, "yscale":3,
        "nodes":[
            { "name": "a", "x": 2.6248, "y": 2.2 },
            { "name": "b", "x": 5.7124, "y": 3.2124 },
            { "name": "c", "x": 8.7503, "y": 3.3248 },
            { "name": "d", "x": 11.9, "y": 1.3 },
            { "name": "e", "x": 2.7503, "y": 4.2621 },
            { "name": "f", "x": 4.6373, "y": 5.6248 },
            { "name": "g", "x": 7.2621, "y": 6.0497 },
            { "name": "h", "x": 9.4621, "y": 5.5497 },
            { "name": "i", "x": 11.3, "y": 4.5 },
            { "name": "j", "x": 1.8, "y": 7.1124 },
            { "name": "k", "x": 3.6248, "y": 7.5876 },
            { "name": "l", "x": 5.2497, "y": 8.4745 },
            { "name": "m", "x": 7.4876, "y": 8.1745 },
            { "name": "n", "x": 9.3419, "y": 8.2601 },
            { "name": "o", "x": 12.5314, "y": 6.4439 },
            { "name": "p", "x": 2.4497, "y": 10.2752 },
            { "name": "q", "x": 3.9248, "y": 9.3627 },
            { "name": "r", "x": 4.5248, "y": 11.9876 },
            { "name": "s", "x": 7.4248, "y": 11.0 },
            { "name": "t", "x": 10.1876, "y": 9.7066 },
            { "name": "u", "x": 12.5379, "y": 10.2503 },
            { "name": "v", "x": 5.4752, "y": 13.2255 },
            { "name": "w", "x": 7.3497, "y": 13.2627 },
            { "name": "x", "x": 9.5373, "y": 12.7248 },
            { "name": "y", "x": 11.2248, "y": 12.6752 },
            { "name": "z", "x": 12.7876, "y": 11.9124 },
            { "name": "A", "x": 2.8621, "y": 14.6752 },
            { "name": "B", "x": 4.6, "y": 17.1124 },
            { "name": "C", "x": 7.2876, "y": 15.7752 },
            { "name": "D", "x": 9.613, "y": 14.0124 },
            { "name": "E", "x": 12.3745, "y": 14.2124 },
            { "name": "F", "x": 2.6124, "y": 18.7 },
            { "name": "G", "x": 6.4, "y": 17.9124 },
            { "name": "H", "x": 8.9248, "y": 17.5124 },
            { "name": "I", "x": 10.4373, "y": 16.1627 },
            { "name": "J", "x": 5.3373, "y": 20.5248 },
            { "name": "K", "x": 7.8, "y": 18.9124 },
            { "name": "L", "x": 11.0497, "y": 19.4503 },
            { "name": "M", "x": 13.1, "y": 18.9124 },
            { "name": "N", "x": 3.8627, "y": 22.4248 },
            { "name": "O", "x": 5.7, "y": 22.2124 },
            { "name": "P", "x": 7.6745, "y": 22.1373 },
            { "name": "Q", "x": 10.2, "y": 21.4745 },
            { "name": "R", "x": 12.4373, "y": 20.913 },
            { "name": "S", "x": 2.6, "y": 24.3497 },
            { "name": "T", "x": 5.9248, "y": 24.4621 },
            { "name": "U", "x": 9.5124, "y": 23.3627 }],
        "links": baranDistributedLinks(),
    },
}
function baranGridNodes() {
    return [
        { "name": "a", "x": 2.0, "y": 1.0 },
        { "name": "b", "x": 3.0, "y": 1.0 },
        { "name": "c", "x": 5.0, "y": 1.0 },
        { "name": "d", "x": 6.0, "y": 1.0 },
        { "name": "e", "x": 2.0, "y": 2.0 },
        { "name": "f", "x": 3.0, "y": 2.0 },
        { "name": "g", "x": 4.0, "y": 2.0 },
        { "name": "h", "x": 5.0, "y": 2.0 },
        { "name": "i", "x": 6.0, "y": 2.0 },
        { "name": "j", "x": 1.0, "y": 3.0 },
        { "name": "k", "x": 2.0, "y": 3.0 },
        { "name": "l", "x": 3.0, "y": 3.0 },
        { "name": "m", "x": 4.0, "y": 3.0 },
        { "name": "n", "x": 5.0, "y": 3.0 },
        { "name": "o", "x": 6.0, "y": 3.0 },
        { "name": "p", "x": 1.0, "y": 5.0 },
        { "name": "q", "x": 2.0, "y": 4.0 },
        { "name": "r", "x": 2.0, "y": 5.0 },
        { "name": "s", "x": 3.0, "y": 4.0 },
        { "name": "t", "x": 5.0, "y": 4.0 },
        { "name": "u", "x": 6.0, "y": 4.0 },
        { "name": "v", "x": 3.0, "y": 5.0 },
        { "name": "w", "x": 4.0, "y": 6.0 },
        { "name": "x", "x": 4.0, "y": 5.0 },
        { "name": "y", "x": 5.0, "y": 5.0 },
        { "name": "z", "x": 6.0, "y": 5.0 },
        { "name": "A", "x": 1.0, "y": 6.0 },
        { "name": "B", "x": 2.0, "y": 6.0 },
        { "name": "C", "x": 3.0, "y": 7.0 },
        { "name": "D", "x": 5.0, "y": 7.0 },
        { "name": "E", "x": 6.0, "y": 7.0 },
        { "name": "F", "x": 1.0, "y": 8.0 },
        { "name": "G", "x": 2.0, "y": 8.0 },
        { "name": "H", "x": 3.0, "y": 8.0 },
        { "name": "I", "x": 5.0, "y": 8.0 },
        { "name": "J", "x": 2.0, "y": 9.0 },
        { "name": "K", "x": 3.0, "y": 9.0 },
        { "name": "L", "x": 4.0, "y": 9.0 },
        { "name": "M", "x": 5.0, "y": 9.0 },
        { "name": "N", "x": 1.0, "y":10.0 },
        { "name": "O", "x": 2.0, "y":10.0 },
        { "name": "P", "x": 3.0, "y":10.0 },
        { "name": "Q", "x": 4.0, "y":10.0 },
        { "name": "R", "x": 5.0, "y":10.0 },
        { "name": "S", "x": 1.0, "y":11.0 },
        { "name": "T", "x": 2.0, "y":11.0 },
        { "name": "U", "x": 4.0, "y":11.0 }
    ];
}
function baranDistributedLinks() {
    return [
        {"name":"la","nodeIDs":["a","b"]},
        {"name":"lb","nodeIDs":["a","e"]},
        {"name":"lc","nodeIDs":["b","c"]},
        {"name":"ld","nodeIDs":["b","f"]},
        {"name":"le","nodeIDs":["b","g"]},
        {"name":"lf","nodeIDs":["c","d"]},
        {"name":"lg","nodeIDs":["c","g"]},
        {"name":"lh","nodeIDs":["c","h"]},
        {"name":"li","nodeIDs":["d","i"]},
        {"name":"lj","nodeIDs":["e","f"]},
        {"name":"lk","nodeIDs":["e","j"]},
        {"name":"ll","nodeIDs":["f","g"]},
        {"name":"lm","nodeIDs":["f","k"]},
        {"name":"ln","nodeIDs":["f","l"]},
        {"name":"lo","nodeIDs":["g","h"]},
        {"name":"lp","nodeIDs":["g","m"]},
        {"name":"lq","nodeIDs":["h","i"]},
        {"name":"lr","nodeIDs":["h","n"]},
        {"name":"ls","nodeIDs":["i","o"]},
        {"name":"lt","nodeIDs":["j","k"]},
        {"name":"lu","nodeIDs":["j","p"]},
        {"name":"lv","nodeIDs":["k","l"]},
        {"name":"lw","nodeIDs":["k","q"]},
        {"name":"lx","nodeIDs":["l","m"]},
        {"name":"ly","nodeIDs":["l","q"]},
        {"name":"lz","nodeIDs":["l","s"]},
        {"name":"lA","nodeIDs":["m","n"]},
        {"name":"lB","nodeIDs":["m","s"]},
        {"name":"lC","nodeIDs":["n","o"]},
        {"name":"lD","nodeIDs":["n","t"]},
        {"name":"lE","nodeIDs":["o","t"]},
        {"name":"lF","nodeIDs":["o","u"]},
        {"name":"lG","nodeIDs":["p","q"]},
        {"name":"lH","nodeIDs":["p","r"]},
        {"name":"lI","nodeIDs":["p","A"]},
        {"name":"lJ","nodeIDs":["q","r"]},
        {"name":"lK","nodeIDs":["r","s"]},
        {"name":"lL","nodeIDs":["r","v"]},
        {"name":"lM","nodeIDs":["r","A"]},
        {"name":"lN","nodeIDs":["s","t"]},
        {"name":"lO","nodeIDs":["s","w"]},
        {"name":"lP","nodeIDs":["s","x"]},
        {"name":"lQ","nodeIDs":["t","u"]},
        {"name":"lR","nodeIDs":["t","x"]},
        {"name":"lS","nodeIDs":["t","y"]},
        {"name":"lT","nodeIDs":["u","z"]},
        {"name":"lU","nodeIDs":["v","w"]},
        {"name":"lV","nodeIDs":["v","B"]},
        {"name":"lW","nodeIDs":["v","C"]},
        {"name":"lX","nodeIDs":["w","C"]},
        {"name":"lY","nodeIDs":["w","D"]},
        {"name":"lZ","nodeIDs":["x","y"]},
        {"name":"La","nodeIDs":["x","D"]},
        {"name":"Lb","nodeIDs":["y","z"]},
        {"name":"Lc","nodeIDs":["y","E"]},
        {"name":"Ld","nodeIDs":["z","E"]},
        {"name":"Le","nodeIDs":["A","v"]},
        {"name":"Lf","nodeIDs":["A","B"]},
        {"name":"Lg","nodeIDs":["A","F"]},
        {"name":"Lh","nodeIDs":["B","C"]},
        {"name":"Li","nodeIDs":["B","G"]},
        {"name":"Lj","nodeIDs":["C","D"]},
        {"name":"Lk","nodeIDs":["C","G"]},
        {"name":"Ll","nodeIDs":["C","H"]},
        {"name":"Lm","nodeIDs":["D","E"]},
        {"name":"Ln","nodeIDs":["D","I"]},
        {"name":"Lo","nodeIDs":["E","I"]},
        {"name":"Lp","nodeIDs":["E","M"]},
        {"name":"Lq","nodeIDs":["F","B"]},
        {"name":"Lr","nodeIDs":["F","J"]},
        {"name":"Ls","nodeIDs":["G","H"]},
        {"name":"Lt","nodeIDs":["G","J"]},
        {"name":"Lu","nodeIDs":["G","K"]},
        {"name":"Lv","nodeIDs":["H","I"]},
        {"name":"Lw","nodeIDs":["H","K"]},
        {"name":"Lx","nodeIDs":["H","L"]},
        {"name":"Ly","nodeIDs":["I","L"]},
        {"name":"Lz","nodeIDs":["J","K"]},
        {"name":"LA","nodeIDs":["J","N"]},
        {"name":"LB","nodeIDs":["J","O"]},
        {"name":"LC","nodeIDs":["K","L"]},
        {"name":"LD","nodeIDs":["K","P"]},
        {"name":"LE","nodeIDs":["L","M"]},
        {"name":"LF","nodeIDs":["L","Q"]},
        {"name":"LG","nodeIDs":["L","R"]},
        {"name":"LH","nodeIDs":["M","R"]},
        {"name":"LI","nodeIDs":["N","F"]},
        {"name":"LJ","nodeIDs":["N","O"]},
        {"name":"LK","nodeIDs":["O","P"]},
        {"name":"LL","nodeIDs":["O","T"]},
        {"name":"LM","nodeIDs":["P","Q"]},
        {"name":"LN","nodeIDs":["P","U"]},
        {"name":"LO","nodeIDs":["Q","R"]},
        {"name":"LP","nodeIDs":["Q","U"]},
        {"name":"LQ","nodeIDs":["S","N"]},
        {"name":"LR","nodeIDs":["S","T"]},
        {"name":"LS","nodeIDs":["T","U"]},
    ];
}
function baranKleinberg() {
    // Kleinberg links
    return [
        {"name":"LT","nodeIDs":["I","k"],"kleinberg":true},
        {"name":"LU","nodeIDs":["H","h"],"klienberg":true},
        {"name":"LV","nodeIDs":["G","o"],"klienberg":true},
        {"name":"LW","nodeIDs":["Q","j"],"klienberg":true}
    ];
}    
